### ISSUE TITLE
Cannot find name 'Buffer' on ionic serve

### ISSUE THREAD

**Issue by moldstadt** [awslabs/aws-mobile-ionic-sample#2]
I get a lot of errors regarding a missing type definition for Buffer when I try to serve.

@types/node is installed.

I already had typings installed, so I tried reinstalling it as per #1, but that made no difference.

cli packages:

    @ionic/cli-plugin-ionic-angular : 1.4.0 (D:\source\AWS\aws-mobile-ionic-sample-t3\client\node_modules\@ionic\cli-plugin-ionic-angular)
    @ionic/cli-utils                : 1.6.0 (D:\source\AWS\aws-mobile-ionic-sample-t3\client\node_modules\@ionic\cli-utils)
    ionic (Ionic CLI)               : 3.6.0 (D:\source\AWS\aws-mobile-ionic-sample-t3\client\node_modules\ionic)

local packages:

    @ionic/app-scripts : 2.1.3
    Ionic Framework    : ionic-angular 3.6.0

System:

    Android SDK Tools : 26.0.2
    Node              : v7.4.0
    OS                : Windows 8.1
    npm               : 5.3.0

```
$ npm list --depth=0
ionic-tasks@0.0.1 D:\source\AWS\aws-mobile-ionic-sample-t3\client
+-- @angular/common@4.1.3
+-- @angular/compiler@4.1.3
+-- @angular/compiler-cli@4.1.3
+-- @angular/core@4.1.3
+-- @angular/forms@4.1.3
+-- @angular/http@4.1.3
+-- @angular/platform-browser@4.1.3
+-- @angular/platform-browser-dynamic@4.1.3
+-- @ionic-native/core@3.12.1
+-- @ionic-native/splash-screen@3.12.1
+-- @ionic-native/status-bar@3.12.1
+-- @ionic/app-scripts@2.1.3
+-- @ionic/cli-plugin-ionic-angular@1.4.0
+-- @ionic/storage@2.0.1
+-- @types/aws4@1.5.1
+-- @types/crypto-js@3.1.33
+-- @types/node@8.0.23
+-- amazon-cognito-identity-js@1.19.0
+-- aws4@1.6.0
+-- crypto-js@3.1.9-1
+-- immutable@3.8.1
+-- ionic@3.6.0
+-- ionic-angular@3.6.0
+-- ionicons@3.0.0
+-- lodash.groupby@4.6.0
+-- lodash.keyby@4.6.0
+-- lodash.map@4.6.0
+-- lodash.orderby@4.6.0
+-- lodash.values@4.3.0
+-- ng2-charts@1.6.0
+-- querystring-browser@1.0.4
+-- rxjs@5.4.0
+-- sw-toolbox@3.6.0
+-- typescript@2.2.2
+-- uuid@3.1.0
`-- zone.js@0.8.12

npm ERR! peer dep missing: ajv@>=5.0.0, required by ajv-keywords@2.1.0
```

I have also tried upgrading to latest node and ionic-cli, with no difference.

**Comment by jimveloper** [comment]
Had the same problem.  Add the following to the client\tsconfig,json within the compilerOptions section
"types": ["node"],
    "typeRoots": [
      "node_modules/@types"
    ]

**Comment by moldstadt** [comment]
Thanks.  Just saw this now, after I resolved it this morning.  I only needed to add:
"typeRoots": [
    "node_modules/@types"
]
