### ISSUE TITLE
Error: send EHOSTUNREACH 169.254.255.255:41234

### ISSUE THREAD

**Issue by kd7lxl** [awslabs/aws-mobile-ionic-sample#4]
When I get to the `ionic serve` step in the instructions, I get this error:

```
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: send EHOSTUNREACH 169.254.255.255:41234
    at Object._errnoException (util.js:1041:11)
    at _exceptionWithHostPort (util.js:1064:20)
    at SendWrap.afterSend [as oncomplete] (dgram.js:474:11)
```

I'm not sure why it would be trying to contact a link-local address like this or where to go from here.

**Comment by onlybakam** [comment]
i'm seeing similar complaints here: https://forum.ionicframework.com/t/event-js-182-getting-error-from-ionic-serve-immediately/105166

can you try out some of the suggestions in that post?

**Comment by kd7lxl** [comment]
Thanks for the follow-up. Unfortunately none of these suggestions work for me.

* I don't have an iPhone, and no other mobile devices are currently plugged into USB.
* The error paste above was actually after running the command `ionic serve --address=localhost`, so it shouldn't be listening on any extra interfaces.
* One user mentions disabling network sharing. The only network sharing service I have enabled is sshd, which I'd prefer not to disable.
* `ionic serve --verbose` resulted in identical output as above.

Here is the output of `ionic info`:
```
cli packages: (/Users/.../aws-mobile-ionic-sample/client/node_modules)

    @ionic/cli-utils  : 1.10.1
    ionic (Ionic CLI) : 3.10.1

local packages:

    @ionic/app-scripts : 2.1.3
    Ionic Framework    : ionic-angular 3.6.0

System:

    Node : v8.4.0
    npm  : 5.3.0 
    OS   : macOS Sierra
```
Are these versions what you would expect?

One thing I didn't mention before: It runs for a few seconds before the failure. The browser launches, the linter runs in the console and completes, then a few seconds later is when I get the crash. This hints to me that it is a background process of the dev console rather than the web app itself that is crashing.

**Comment by kd7lxl** [comment]
Rolling back to 3.9.2 fixed it.

    npm install ionic@3.9.2

I thumbs-upped the issue over at https://github.com/ionic-team/ionic-cli/issues/2732. Closing here because it seem to be an ionic issue.
