### ISSUE TITLE
realtime - dynamodb

### ISSUE THREAD

**Issue by medbz** [awslabs/aws-mobile-ionic-sample#7]
How it is possible to make the ionic app watch the change activity on the dynamoDB noSQL table . 
My application is based on the realtime solution so please any help? if there is a tutorial or something else please share it with me :D big thanks !

**Comment by undefobj** [comment]
@medbz please take a look at AWS AppSync: https://aws.amazon.com/appsync/

**Comment by medbz** [comment]
There is no other way to do realtime without Appsync ? i mean to use the mobile hub only as i am using ionic aws starter

**Comment by undefobj** [comment]
With just Mobile Hub there is no realtime functionality at this time. You could build this yourself using this project as a starting point - use DynamoDB streams (https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Streams.html) to publish activity either to an AWS IoT topic or an EC2 server with web socket functionality. Then have clients subscribe to channels/topics on that server (or IoT) to receive updates.

**Comment by medbz** [comment]
Thanks alot @undefobj :D
